# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import json
import gmaps
import os
from ipywidgets.embed import embed_minimal_html
# Import API key
from api_keys import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

import warnings
warnings.filterwarnings("ignore")

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
# Import csv file from the output_data folder under WeatherPy and display
csvpath = '../WeatherPy/output_data/cities.csv'
cities_df = pd.read_csv(csvpath, index_col=0)
cities_df

,City,Latitude,Longitude,Max Temperature (Â°C),Humidity (%),Cloudiness (%),Wind Speed (MPH),Country,Date
0,upernavik,72.7868,-56.1549,5.08,93,100,4.12,GL,1628352303
1,san patricio,28.0170,-97.5169,31.99,54,7,5.07,US,1628352237
2,puerto escondido,15.8500,-97.0667,29.46,65,1,0.00,MX,1628352306
3,mataura,-46.1927,168.8643,1.38,98,100,0.61,NZ,1628352307
4,hualmay,-11.0964,-77.6139,19.68,71,45,5.21,PE,1628352310
5,fortuna,40.5982,-124.1573,16.07,96,90,0.00,US,1628352131
6,ponta do sol,32.6667,-17.1000,26.18,80,56,2.20,PT,1628352101
7,aklavik,68.2191,-135.0107,6.00,93,90,5.14,CA,1628352257
8,arica,-18.4750,-70.3042,18.75,67,90,3.60,CL,1628352314
9,oksfjord,70.2396,22.3479,19.51,62,93,0.81,NO,1628352316
10,mayumba,-3.4320,10.6554,23.34,81,100,3.56,GA,1628352317
11,butaritari,3.0707,172.7902,27.73,71,20,5.76,KI,1628352319
12,kapaa,22.0752,-159.3190,26.18,76,40,1.34,US,1628352320
13,hobart,-42.8794,147.3294,3.36,87,33,0.89,AU,1628352321
14,hilo,19.7297,-155.0900,22.85,90,90,2.57,US,1628352186
15,dalby,-27.1833,151.2667,6.59,80,0,2.91,AU,1628352324
16,khatanga,71.9667,102.5000,10.57,71,9,3.03,RU,1628352325
17,hermanus,-34.4187,19.2345,13.28,77,100,1.19,ZA,1628352327
18,bluff,-46.6000,168.3333,1.56,65,100,2.88,NZ,1628352328
19,severnoye,56.3491,78.3619,17.46,89,70,1.62,RU,1628352329
20,russell,32.3502,-85.1999,30.51,64,20,0.00,US,1628352331
21,jamestown,42.0970,-79.2353,27.62,65,1,3.60,US,1628352322
22,ushuaia,-54.8000,-68.3000,0.81,86,75,8.75,AR,1628352333
23,nikolskoye,59.7035,30.7861,16.94,99,100,3.47,RU,1628352335
24,oranjemund,-28.5500,16.4333,16.83,57,21,2.55,NaN,1628352337
25,norman wells,65.2820,-126.8329,6.14,85,100,2.88,CA,1628352212
26,chodavaram,17.8333,82.9500,27.91,79,100,1.20,IN,1628352341
27,hennenman,-27.9765,27.0242,13.15,15,0,2.07,ZA,1628352342
28,qaanaaq,77.4840,-69.3632,5.46,72,91,2.56,GL,1628352188
29,busselton,-33.6500,115.3333,15.05,92,100,6.68,AU,1628352345
...,...,...,...,...,...,...,...,...,...
526,ocos,14.5094,-92.1933,32.92,75,100,0.79,GT,1628353031
527,stabat,3.7610,98.4513,27.11,96,27,1.26,ID,1628353032
528,djenne,13.9061,-4.5533,30.92,53,59,6.86,ML,1628353034
529,winnemucca,40.9730,-117.7357,23.03,18,1,2.57,US,1628353035
530,kolondieba,11.0882,-6.8926,26.21,71,96,3.22,ML,1628353036
531,acapulco,16.8634,-99.8901,29.90,66,75,3.09,MX,1628353037
532,kargasok,59.0556,80.8572,17.70,90,92,2.69,RU,1628353039
533,salina,38.8403,-97.6114,32.32,61,1,4.02,US,1628352985
534,turiacu,-1.6633,-45.3717,29.35,61,24,2.39,BR,1628353041
535,xam nua,20.4197,104.0439,22.26,85,97,1.40,LA,1628353043
536,coacoyul,17.8058,-99.1100,22.90,83,85,1.35,MX,1628353044
537,plettenberg bay,-34.0527,23.3716,15.14,83,94,3.03,ZA,1628353045
538,sabnova,42.0762,48.2480,29.16,46,0,4.11,RU,1628353046
539,novopetrovskoye,55.9928,36.4719,22.56,66,72,1.89,RU,1628353048
540,andrews,32.3187,-102.5457,27.58,69,40,6.17,US,1628353050
541,siemiatycze,52.4272,22.8623,22.92,71,55,3.70,PL,1628353052
542,yar-sale,66.8333,70.8333,19.49,68,15,2.39,RU,1628353053
543,naze,28.3667,129.4833,26.66,85,100,5.92,JP,1628353054
544,suffolk,40.8668,-72.7996,30.30,71,1,1.34,US,1628353055
545,leh,34.1667,77.5833,19.77,31,26,3.24,IN,1628353057
546,hai duong,20.9333,106.3167,34.06,78,100,2.92,VN,1628353058
547,kupang,-10.1667,123.5833,23.98,69,10,5.40,ID,1628353059
548,belyy yar,53.6039,91.3903,15.94,100,0,1.00,RU,1628353061
549,kailua,21.4022,-157.7394,24.99,71,20,5.14,US,1628353062
550,padang,-0.9492,100.3543,26.19,86,22,1.61,ID,1628353063
551,buritizeiro,-17.3511,-44.9622,25.43,36,100,3.50,BR,1628353065
552,enniscorthy,52.5008,-6.5578,17.87,87,100,7.95,IE,1628353066
553,dunyapur,29.7995,71.7196,36.01,35,13,3.78,PK,1628353067
554,hovd,48.0056,91.6419,14.97,61,72,2.07,MN,1628352849
555,port augusta,-32.5000,137.7667,9.28,76,0,2.22,AU,1628353070

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Use Latitude and Longitude as the locations, and humidity as weights for the heat layer
locations = cities_df[["Latitude", "Longitude"]]
humidity = cities_df['Humidity (%)'].astype(float)

# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius=2)

# Add layer
fig.add_layer(heat_layer)

# Display figure
fig
#embed_minimal_html('export_heatmap.html', views=[fig])

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [4]:
# Filter out those cities that satisfy the requirement listed in the instruction
ideal_cities_df = cities_df.loc[(cities_df['Max Temperature (Â°C)'] > 21.11) &
                        (cities_df['Max Temperature (Â°C)'] < 26.67) & 
                        (cities_df['Wind Speed (MPH)'] < 10) &
                        (cities_df['Cloudiness (%)'] == 0)
                       ]

# If is null value, drop it
hotel_df = ideal_cities_df.dropna()

# Print out the number of cities and display the dataframe
print(f'There are {len(hotel_df)} ideal cities for vacation')
hotel_df

There are 9 ideal cities for vacation

,City,Latitude,Longitude,Max Temperature (Â°C),Humidity (%),Cloudiness (%),Wind Speed (MPH),Country,Date
63,thabazimbi,-24.5917,27.4116,21.42,18,0,1.95,ZA,1628352391
193,chadiza,-14.0678,32.4392,22.19,29,0,3.06,ZM,1628352571
229,luanda,-8.8368,13.2343,24.00,83,0,3.60,AO,1628352405
381,umea,63.8284,20.2597,21.96,40,0,5.66,SE,1628352837
444,saint-francois,46.4154,3.9054,21.69,49,0,7.72,FR,1628352920
449,santa maria,-29.6842,-53.8069,26.61,44,0,5.66,BR,1628352927
486,nouadhibou,20.9310,-17.0347,24.99,69,0,5.14,MR,1628352976
500,metro,-5.1131,105.3067,24.71,86,0,2.27,ID,1628352994
507,chifeng,42.2683,118.9636,21.40,59,0,2.45,CN,1628352962

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [5]:
# Convert the Latitude and Longitude to a list for searching, and set up an empty list for appending hotel names
Latitude = hotel_df['Latitude'].tolist()
Longitude = hotel_df['Longitude'].tolist()
hotel_lst = []

# Get the first hotel that came up in the search for each cities
for i in range(len(hotel_df)):
    target_coordinates = f"{Latitude[i]}, {Longitude[i]}"
    target_search = 'hotel'
    target_type = "hotel"
    target_radius = 5000

    # Set up a parameters dictionary
    params = {
        "location": target_coordinates,
        "types": target_type,
        "keyword": target_search,
        "radius": target_radius,
        "key": g_key
    }
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # Use a try and except block to ensure that the code won't stop when no hotel is found
    try:
        
        # Run a request using params dictionary
        response = requests.get(base_url, params=params).json()
        hotel_lst.append(response['results'][0]['name'])
    
    except:
        
        # Append the string to indicate no hotel was found
        hotel_lst.append('NO HOTEL FOUND')
        
# After the loop, add the hotel list as a column in the dataframe
hotel_df['Hotel Name'] = hotel_lst

In [6]:
# Display the dataframe
hotel_df

,City,Latitude,Longitude,Max Temperature (Â°C),Humidity (%),Cloudiness (%),Wind Speed (MPH),Country,Date,Hotel Name
63,thabazimbi,-24.5917,27.4116,21.42,18,0,1.95,ZA,1628352391,NO HOTEL FOUND
193,chadiza,-14.0678,32.4392,22.19,29,0,3.06,ZM,1628352571,NO HOTEL FOUND
229,luanda,-8.8368,13.2343,24.00,83,0,3.60,AO,1628352405,NO HOTEL FOUND
381,umea,63.8284,20.2597,21.96,40,0,5.66,SE,1628352837,NO HOTEL FOUND
444,saint-francois,46.4154,3.9054,21.69,49,0,7.72,FR,1628352920,NO HOTEL FOUND
449,santa maria,-29.6842,-53.8069,26.61,44,0,5.66,BR,1628352927,NO HOTEL FOUND
486,nouadhibou,20.9310,-17.0347,24.99,69,0,5.14,MR,1628352976,NO HOTEL FOUND
500,metro,-5.1131,105.3067,24.71,86,0,2.27,ID,1628352994,NO HOTEL FOUND
507,chifeng,42.2683,118.9636,21.40,59,0,2.45,CN,1628352962,NO HOTEL FOUND

In [7]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]

In [8]:
# Add marker layer with infobox ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)

# Display figure
fig.add_layer(markers)
#embed_minimal_html('export_hotels.html', views=[fig])
fig

Figure(layout=FigureLayout(height='420px'))